create table "public"."prompts" (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    prompt_name text not null default 'Default',
    prompt_body text not null default ''
);

alter table
    "public"."prompts" enable row level security;

create policy "Allow logged-in read access to prompts." on public.prompts for
select
    using (auth.uid() = user_id);

create policy "Allow full access to own prompts" on "public"."prompts" as permissive for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));